export const Bankfee = require('./Bank fee.svg');
export const Commute = require('./Commute.svg');
export const Salary = require('./Salary.svg');
export const Insurance = require('./Insurance.svg');
export const ChildBenefit = require('./Child benefit.svg');
export const Childcare = require('./Childcare.svg');
export const Food = require('./Food.svg');
export const Housing = require('./Housing.svg');
export const Sport = require('./Sport Activities.svg');
export const Clothing = require('./Clothing.svg');
export const EntertainmentElectronics = require('./Entertainment Electronics.svg');
export const EntertainmentSubscriptions = require('./Entertainment Subscriptions.svg');
export const EntertainmentHobby = require('./Entertainment Hobby.svg');
export const Phone = require('./Phone.svg');
export const Internet = require('./Internet.svg');
export const Computer = require('./Computer.svg');
export const Giving = require('./Giving.svg');
export const Studentloan = require('./Student loan.svg');
export const Electricalbill = require('./Electrical bill.svg');
export const Travel = require('./Travel.svg');
export const Car = require('./Car.svg');

export default Commute;
